n = int(input())
a = list(map(int, input().split()))
b = list(map(int, input().split()))
max_win = min(a[0],b[1]) + min(a[1],b[2]) + min(a[2],b[0])
min_win = n - (min(a[0],b[0]+b[2]) + min(a[1],b[1]+b[0]) + min(a[2],b[2]+b[1]))
print(min_win)
print(max_win)